#SourcingSauce: https://github.com/kubernetes-sigs/controller-tools/blob/main/.github/dependabot.yml

version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-github-actions:
        patterns: [ "*" ]
    commit-message:
      prefix: ":seedling:"
    labels:
    - "ok-to-test"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    # group all dependencies with a k8s.io prefix into a single PR.
    groups:
      all-go-mod-patch-and-minor:
        patterns: [ "*" ]
        update-types: [ "patch", "minor" ]
    ignore:
    # Ignore k8s and its transitives modules as they are upgraded manually.
    - dependency-name: "k8s.io/*"
      update-types: [ "version-update:semver-major", "version-update:semver-minor" ]
    commit-message:
      prefix: ":seedling:"
    labels:
      - "ok-to-test"
