---
##### CI for use by github no need for action to be added
##### Inherited
ci:
  autofix_prs: false
  skip: [detect-aws-credentials, ansible-lint]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Safety
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: trailing-whitespace

      # git checks
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-case-conflict

      # General checks
      - id: trailing-whitespace
      # - id: check-yaml
      - id: end-of-file-fixer

  - repo: https://github.com/golangci/golangci-lint
    rev: v1.52.2
    hooks:
      - id: golangci-lint

  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.19.1
    hooks:
      - id: gitleaks

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.22
    hooks:
      - id: helmlint
      - id: packer-validate


  - repo: https://github.com/norwoodj/helm-docs
    rev: "v1.14.2"
    hooks:
      - id: helm-docs
        args:
          # Make the tool search for charts only under the `charts` directory
          - --chart-search-root=charts

  - repo: local
    hooks:
      - id: kubebuilder-generate
        name: Run kubebuilder generate
        entry: make generate
        language: system
        pass_filenames: false
      - id: make-manifests
        name: Run make manifests
        entry: make manifests
        language: system
        pass_filenames: false
