# DefaultDir: "packer"
# Finalizer: "ami.refresher.ops/finalizer"
# GitSyncContainerName: "git-sync"
# Name: "ami-refresh-operator"
# PackerContainerName: "packer"
# StorageType: "etcd"
# StoreTypeEtcd: "etcd"
# StoreTypeSQLite: "sqlite"
# TagActive: "active"
# TagBaseAMI: "base-ami"
# TagBuilderID: "builder-id"
# TagClusterName: "cluster-name"
# TagCreatedBy: "brought-to-you-in-part-by"
# TagCreationTimestamp: "creation-timestamp"
# TagJobID: "job-id"
# TagRegion: "region"
# TagStatus: "status"
# Tags:
#   - "base-ami"
#   - "builder-id"
#   - "cluster-name"
#   - "job-id"
#   - "brought-to-you-in-part-by"
#   - "region"
#   - "creation-timestamp"
