---
- name: Apply CIS Hardening to Amazon Linux 2023
  hosts: localhost
  become: yes
  roles:
    - AMAZON2023-CIS

  # https://github.com/ansible-lockdown/AMAZON2023-CIS/blob/devel/defaults/main.yml
  vars:
    setup_audit: true
    run_audit: true
    amzn2023cis_rule_4_6_6: false
    amzn2023cis_config_aide: false
    amzn2023cis_syslog_service: external
    amzn2023cis_selinux_disable: true
    amzn2023cis_rule_1_2_1: false
    amzn2023cis_rule_1_3_1: false
    amzn2023cis_rule_1_3_3: false
    amzn2023cis_rule_6_2_10: false
    amzn2023cis_rule_1_1_2_3: false
    amzn2023cis_rule_1_1_4_3: false
    amzn2023cis_rule_3_2_1: false
