---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ami.opsy.dev
  resources:
  - amirefreshers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ami.opsy.dev
  resources:
  - amirefreshers/finalizers
  verbs:
  - update
- apiGroups:
  - ami.opsy.dev
  resources:
  - amirefreshers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ami.opsy.dev
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ami.opsy.dev
  resources:
  - packerbuilders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ami.opsy.dev
  resources:
  - packerbuilders/finalizers
  verbs:
  - update
- apiGroups:
  - ami.opsy.dev
  resources:
  - packerbuilders/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ami.opsy.dev
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ami.opsy.dev
  resources:
  - pods/log
  verbs:
  - get
  - list
  - watch
