apiVersion: ami.opsy.dev/v1alpha1
kind: AMIRefresher
metadata:
  labels:
    app.kubernetes.io/name: amirefresher
    app.kubernetes.io/instance: amirefresher-sample
    app.kubernetes.io/part-of: opsy-ami-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: opsy-ami-operator
  name: amirefresher-sample
spec:
  # TODO(user): Add fields here
