apiVersion: v2
name: opsy-ami-operator
description: >-
  A Helm chart for The Opsy AMI Operator is designed to automate the process of
  building AMIs using Packer and refreshing AMIs for EKS node groups.
type: application
version: 1.6.0
appVersion: 1.6.0
maintainers:
  - email: info@ibeify.io
    name: Ibeify Operator
