# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "opsy-ami-operator.fullname" . }}-controller-manager-metrics-monitor
  labels:
    control-plane: controller-manager
    app.kubernetes.io/component: metrics
    app.kubernetes.io/created-by: opsy-ami-operator
    app.kubernetes.io/part-of: opsy-ami-operator
  {{- include "opsy-ami-operator.labels" . | nindent 4 }}
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      control-plane: controller-manager
  {{- include "opsy-ami-operator.selectorLabels" . | nindent 4 }}