apiVersion: v1
kind: ServiceAccount
metadata:
  name: { { include "node-group-opsy-ami-operator.fullname" . } }
  labels: { { - include "node-group-opsy-ami-operator.labels" . | nindent 4 } }
  annotations:
    eks.amazonaws.com/role-arn:
      { { .Values.serviceAccount.annotations.roleArn } }
