apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opsy-ami-operator.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: opsy-ami-operator
    app.kubernetes.io/part-of: opsy-ami-operator
  {{- include "opsy-ami-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}